// import topcourse1 from "../assets/Images/topcourse1"
export const gallery = [
    {
        img:"src/assets/Images/topcourse1.jpg",
        title:"1WordPress Theme Development with Bootstrap",
        para:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Aliquid, perspiciatis?",
        color:"#ffc5f6",
        star:"#ff5be6",
        offerPrice:"$10",
        realPrice:"$11.99",
        status:"Intermediate",
    },
    {
        img:"src/assets/Images/topcourse2.jpg",
        title:"2WordPress Theme Development with Bootstrap",
        para:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Aliquid, perspiciatis?",
        color:"#b9ffa1",
        star:"#3ae941",
        offerPrice:"$12",
        realPrice:"$18.99",
        status:"Advanced",

    },
    {
        img:"src/assets/Images/topcourse3.jpg",
        title:"3WordPress Theme Development with Bootstrap",
        para:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Aliquid, perspiciatis?",
        color:"#b9ffa1",
        star:"#3ae941",
        offerPrice:"$12",
        realPrice:"$149.99",
        status:"Beginner",
    },
    {
        img:"src/assets/Images/topcourse4.jpg",
        title:"4WordPress Theme Development with Bootstrap",
        para:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Aliquid, perspiciatis?",
        color:"#b9ffa1",
        star:"#3ae941",
        offerPrice:"Free",
        realPrice:"",
        status:"Intermediate",
    },
    {
        img:"src/assets/Images/topcourse5.jpg",
        title:"WordPress Theme Development with Bootstrap",
        para:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Aliquid, perspiciatis?",
        color:"#fff3b5",
        star:"#ffb629",
        offerPrice:"$13",
        realPrice:"$29.99",
        status:"Beginner",
    },
    {
        img:"src/assets/Images/topcourse6.jpg",
        title:"WordPress Theme Development with Bootstrap",
        para:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Aliquid, perspiciatis?",
        color:"#b9ffa1",
        star:"#3ae941",
        offerPrice:"$58",
        realPrice:"$158",
        status:"Advanced",
    },
    {
        img:"src/assets/Images/topcourse7.jpg",
        title:"WordPress Theme Development with Bootstrap",
        para:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Aliquid, perspiciatis?",
        color:"#fff3b5",
        star:"#ffb629",
        offerPrice:"$56",
        realPrice:"$89.99",
        status:"Beginner",
    },
    {
        img:"src/assets/Images/topcourse7.jpg",
        title:"WordPress Theme Development with Bootstrap",
        para:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Aliquid, perspiciatis?",
        color:"#ffc5f6",
        star:"#ff5be6",
        offerPrice:"$1800",
        realPrice:"$1896",
        status:"Advance",
    },
   
]